/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.Scanner;
import java.io.BufferedReader;
import java.io.FileReader;

import org.example.ui.SimulatorApp;
import org.example.util.CalculateGraph;
import org.example.util.Night;
import org.knowm.xchart.QuickChart;
import org.knowm.xchart.SwingWrapper;
import org.knowm.xchart.XYChart;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException{
        // Launch Swing-based simulator UI by default
        // SimulatorApp.launchSwing(args);
        ArrayList<Night> nights = new ArrayList<Night>();
        //File file = new File("data.csv");
        BufferedReader scanner = new BufferedReader(new FileReader("template-data.csv"));
        // Scanner scanner = new Scanner(file);
        String line = "";
        while((line = scanner.readLine()) != null) {
            String[] night = line.split(",");
            nights.add(new Night(new Date(CalculateGraph.daysToMilliseconds(Integer.parseInt(night[0]))), Double.parseDouble(night[1])));
        }

        CalculateGraph.computeValues(nights);
        // new SimulatorApp().start();

        scanner.close();
    }
}
