/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.5.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("com.diffplug.spotless") version "6.21.0"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)

    // Use XChart (Swing) for charts in a lightweight, cross-platform way
    implementation("org.knowm.xchart:xchart:3.8.5")

    // LGoodDatePicker to choose calendar days
    implementation("com.github.lgooddatepicker:LGoodDatePicker:11.2.1")

    // Guava library to use the Double.tryParse() method for more elegant input validation
    implementation("com.google.guava:guava:33.6.0-jre")

    // Use Apache Commons CSV for robust, RFC4180-compliant CSV parsing (handles quoted fields, embedded commas)
    implementation("org.apache.commons:commons-csv:1.10.0")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.example.App"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

spotless {
    java {
        target("src/**/*.java")
        // Use Google Java Format for consistent, modern Java formatting
        googleJavaFormat("1.17.0")
    }
}
